
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: baseball_card_development

test:
  <<: *default
  database: baseball_card_test

production:
  <<: *default
  database: baseball_card_production
  # username: baseball-card
  # password: <%= ENV['WILDLIFE_TRACKER_DATABASE_PASSWORD'] %>
